### ISSUE TITLE
A question about deflation.m

### ISSUE THREAD

**Issue by ConanZH429** [janverschelde/PHClab#3] opened 2020-08-19 16:19 UTC
Output is opened on line 51 of the file, but output has not been created before. So my program is running wrong. Could you please answer my question?

Here is my code. I use deflation at the end of my code, but it comes back wrong.

set_phcpath('C:\Users\lenovo\Desktop\PHClab1.0.4\phc.exe')

% tableau input for a system :
t = [1.3 2 0; 4.7 0 2; -3.1 + 2.3*i 0 0; 0 0 0;
       2.1 0 2; -1.9 1 0; 0 0 0];
make_system(t) % shows symbolic format of the system
s = solve_system(t); % call the blackbox solver
ns = size(s,2) % check the number of solutions
s3 = s(3) % look at the 3rd solution

double = [1.0 2 0; 4.0 0 2; -4.0 0 0; 0 0 0;
               -2.0 0 2; +1.0 1 0; -2.0 0 0; 0 0 0];
make_system(double) % shows symbolic format of the system
s(1).time = 0; s(2).time = 0; % initialize time for every start
s(3).time = 0; s(4).time = 0; % solution to zero
sols = track(double,t,s); % call the blackbox solver
ns = size(sols,2) % check the number of solutions
s2 = sols(2) % look at the 2nd solution

r2 = refine_sols(double,s2,1.0e-16,1.0e-08,1.0e-16,10)

def_sols = deflation(double,sols);
def_sols{4,1}

**Comment by janverschelde** [comment] 2020-08-21 02:06
Thanks for reporting this issue.  I could reproduce your error.
The problem is in the script that makes the input file on line 40 of deflation.m.
The user input no longer corresponds with the newest version of phc.
I will try to fix this soon.

**Comment by ConanZH429** [comment] 2020-08-22 03:32
It seems to be a problem with functions that are numerically irreducible, like embed and decompose.

I will be very, very, very grateful to you if you can solve these problems.

The project you and your team have developed has made a great contribution to scientific research and application. 

Thank you again sincerely.

**Comment by janverschelde** [comment] 2020-08-31 18:03
The deflation.m has been corrected and tested with Octave 5.2.0.
Please verify that it works with MATLAB, and then please close the issue,
otherwise submit another comment.

For the numerical irreducible decomposition functions, please open separate issues.

**Closed as completed** 2020-11-11 00:15 UTC
